# Generated by Django 6.0 on 2026-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECURecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50)),
                ('ecu_id', models.CharField(max_length=20, unique=True)),
                ('sw_version', models.CharField(max_length=50)),
                ('prng_type', models.CharField(max_length=20)),
                ('password_length', models.IntegerField()),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
