# Generated by Django 6.0 on 2026-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECUConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ecu_id', models.CharField(max_length=100, unique=True)),
                ('last_serial', models.IntegerField(default=0)),
            ],
        ),
    ]
