# Generated by Django 6.0.1 on 2026-02-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0002_ecuconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('POWER_USER', 'Power User'), ('RESTRICTED', 'Restricted User'), ('GUEST', 'Guest')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
