# Generated by Django 6.0.1 on 2026-02-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0003_systemuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('OEM', 'OEM'), ('INTERMEDIATE', 'INTERMEDIATE'), ('SIGNING', 'SIGNING')], max_length=20)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
