# Generated by Django 6.0.1 on 2026-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0004_keypair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ECURecord',
        ),
        migrations.DeleteModel(
            name='SystemUser',
        ),
        migrations.AlterField(
            model_name='keypair',
            name='key_type',
            field=models.CharField(max_length=50),
        ),
    ]
